import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavLink from "@/components/NavLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{ background: "var(--background)", color: "var(--foreground)" }}
      >
        <header className="flex fixed p-5 pl-10 justify-between text-2xl font-bold font-mono bg-[#1e453e] top-0 w-full shadow-[0_10px_20px_rgba(0,0,0,0.5)] z-50">
          <NavLink href="/">this is je.</NavLink>
          <div className="flex gap-10 text-lg pr-10 pl-10 font-light">
            <NavLink href="/gamedev">gameDev</NavLink>
            <NavLink href="/softwaredev">softwareDev</NavLink>
            <NavLink href="/leadership">leadership</NavLink>
            <NavLink href="/creatives">creatives</NavLink>
            <NavLink href="/info">info</NavLink>
          </div>
        </header>
        <main className="m-35">
          {children}
        </main>
      </body>
    </html>
  );
}
